import './_vendor';
import vars from './_vars';
import './_functions';
import './_components';
import './components/slider';
import './components/tabs';
import './components/clients-slider';
import './components/show-modal';
import './components/modal-form';
import './components/modal-validation';
